In [1]:
import tensorflow as tf

D:\python\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [9]:
img = tf.random_uniform([10,28,28,3])
with tf.Session() as sess1:
    print(sess1.run(img))

[[[[0.3973292  0.6203015  0.28502452]
   [0.7358917  0.8890619  0.28081155]
   [0.17974734 0.07289636 0.20222628]
   ...
   [0.34600222 0.2218622  0.57747805]
   [0.03400171 0.50779593 0.6643622 ]
   [0.86796844 0.81675935 0.5466701 ]]

  [[0.7545569  0.94460046 0.00850201]
   [0.5522208  0.3662318  0.06985331]
   [0.94344425 0.8485662  0.35317838]
   ...
   [0.104334   0.24789166 0.7565323 ]
   [0.8373065  0.58183587 0.4093156 ]
   [0.10776508 0.36721087 0.7870358 ]]

  [[0.60607743 0.39553392 0.8727931 ]
   [0.8668717  0.03913021 0.11664391]
   [0.5219425  0.49756706 0.7614771 ]
   ...
   [0.91333544 0.34575498 0.9764651 ]
   [0.6651635  0.31396675 0.48736668]
   [0.8338618  0.28988755 0.07021666]]

  ...

  [[0.65842545 0.03083801 0.9926765 ]
   [0.64859676 0.04974222 0.04894125]
   [0.5447562  0.06457448 0.54744303]
   ...
   [0.7109854  0.23519301 0.79734814]
   [0.20385933 0.81260705 0.14526975]
   [0.7419293  0.5774988  0.1503601 ]]

  [[0.7437568  0.14445388 0.61098766]
   [0.8

In [13]:
#索引
a = img[1:2,0:,0:,0:]
with tf.Session() as sess2:
    print(sess2.run(a))

[[[[0.37491822 0.7486589  0.9637722 ]
   [0.968228   0.2674787  0.45921016]
   [0.42298496 0.8425863  0.6484357 ]
   ...
   [0.20417023 0.21321154 0.14434147]
   [0.28971934 0.35834014 0.3139919 ]
   [0.636708   0.2598014  0.27283692]]

  [[0.37985086 0.40512347 0.8246021 ]
   [0.34400618 0.9305093  0.6374029 ]
   [0.6859114  0.8284162  0.15781403]
   ...
   [0.33791745 0.75921035 0.38814485]
   [0.08942115 0.68610847 0.83578706]
   [0.87754476 0.89934504 0.30248368]]

  [[0.1543765  0.8730855  0.63038146]
   [0.22880113 0.13293123 0.6168097 ]
   [0.73360145 0.50633955 0.8991332 ]
   ...
   [0.8659936  0.18443203 0.4645164 ]
   [0.41269112 0.29400837 0.8833401 ]
   [0.33943188 0.89811707 0.57948005]]

  ...

  [[0.7224169  0.43065834 0.54351103]
   [0.2770455  0.07139504 0.2813964 ]
   [0.9553995  0.56968653 0.44302046]
   ...
   [0.09378052 0.10092211 0.9996989 ]
   [0.77292717 0.9494672  0.3117447 ]
   [0.54397094 0.21480262 0.11803353]]

  [[0.7563374  0.37466156 0.6164001 ]
   [0.3

In [14]:
#切片
b = tf.slice(img,[1,0,0,0],[1,28,28,3])
with tf.Session() as sess3:
    print(sess3.run(b))

[[[[0.54331195 0.5914533  0.04778588]
   [0.7357278  0.17780328 0.98206997]
   [0.8032882  0.571995   0.16867173]
   ...
   [0.19479048 0.9901813  0.12248123]
   [0.91613686 0.08734107 0.6418276 ]
   [0.59736407 0.09160554 0.11514568]]

  [[0.18365788 0.28564835 0.41919553]
   [0.9528425  0.8920196  0.7061665 ]
   [0.6420803  0.82092655 0.6846951 ]
   ...
   [0.77032804 0.7763324  0.1999135 ]
   [0.7034085  0.17878914 0.89087474]
   [0.01300764 0.12443602 0.44377232]]

  [[0.34816337 0.67808735 0.99485767]
   [0.9416379  0.65769553 0.48483944]
   [0.49413502 0.5878155  0.6977091 ]
   ...
   [0.1722554  0.16487777 0.54213417]
   [0.7406993  0.2827605  0.7421764 ]
   [0.17525661 0.32558382 0.47932076]]

  ...

  [[0.2636596  0.49904454 0.9317285 ]
   [0.974064   0.73644257 0.8733783 ]
   [0.74044454 0.845855   0.9668058 ]
   ...
   [0.74919164 0.71687424 0.56876683]
   [0.68691146 0.05062962 0.13332272]
   [0.559741   0.17646074 0.09062123]]

  [[0.4016081  0.79377866 0.82761395]
   [0.1

In [22]:
#取出1 3 5 7 张图片
for i in range (1,4):
    j=1
    c = tf.slice(img,[j-1,0,0,0],[1,28,28,3]) 
    j=j+2
    with tf.Session() as sess4:
        print(sess4.run(c))

[[[[0.5083828  0.01088631 0.22083318]
   [0.4820149  0.445045   0.9625517 ]
   [0.899544   0.32493114 0.4541968 ]
   ...
   [0.8890116  0.13884294 0.95897925]
   [0.8062767  0.12986445 0.44940257]
   [0.79874575 0.33068085 0.37848878]]

  [[0.65487564 0.29815006 0.9651288 ]
   [0.06749094 0.1252451  0.72386205]
   [0.23923612 0.915017   0.6291914 ]
   ...
   [0.6535044  0.613284   0.21211505]
   [0.5550724  0.9240639  0.3938377 ]
   [0.7370664  0.31520665 0.16096592]]

  [[0.11046267 0.07467926 0.03984642]
   [0.56316185 0.03260076 0.346138  ]
   [0.1489346  0.25606406 0.45131838]
   ...
   [0.88354075 0.23553467 0.41069126]
   [0.15725851 0.6806203  0.22207701]
   [0.66460407 0.14590621 0.6521932 ]]

  ...

  [[0.67538106 0.43318975 0.48868048]
   [0.6668153  0.58370674 0.5019728 ]
   [0.94294775 0.9247731  0.29721558]
   ...
   [0.25436687 0.6237198  0.757344  ]
   [0.03890741 0.9045849  0.61494124]
   [0.26754642 0.56384945 0.70761347]]

  [[0.7178905  0.54130423 0.6176847 ]
   [0.3

In [16]:
#第七张中心区域
d = tf.slice(img,[6,7,7,0],[1,14,14,3])
with tf.Session() as sess5:
    print(sess5.run(d))

[[[[4.97571111e-01 7.48195767e-01 5.52580833e-01]
   [9.61450338e-02 6.67892694e-02 6.45156026e-01]
   [3.72190595e-01 6.69217825e-01 3.32198381e-01]
   [9.70152974e-01 8.82359028e-01 4.95368004e-01]
   [4.13546562e-02 3.50492120e-01 9.17172432e-03]
   [9.96619582e-01 3.17951560e-01 5.01537204e-01]
   [3.07603955e-01 8.97945166e-02 7.74059296e-02]
   [1.31615281e-01 3.40060353e-01 3.67273331e-01]
   [3.59824538e-01 5.60266733e-01 6.40127659e-02]
   [5.62847018e-01 3.98113728e-02 7.50298023e-01]
   [4.39345837e-01 9.80238557e-01 6.69753909e-01]
   [3.21674347e-01 4.23024416e-01 3.05892229e-01]
   [2.79480219e-02 6.18753433e-01 3.78955960e-01]
   [2.42679715e-01 3.90422225e-01 2.06338525e-01]]

  [[3.57769728e-02 4.29938793e-01 5.96003532e-01]
   [4.42106009e-01 5.82805872e-02 8.74773026e-01]
   [6.13565683e-01 4.12866950e-01 9.25741196e-02]
   [7.08794475e-01 4.68364120e-01 7.34183669e-01]
   [1.00186586e-01 3.82743239e-01 6.78276062e-01]
   [7.73441792e-01 4.09871221e-01 6.13044739e-01

In [17]:
#拆分成三份单通道
e = tf.slice(img,[0,0,0,0],[10,28,28,1])
f = tf.slice(img,[0,0,0,1],[10,28,28,1])
g = tf.slice(img,[0,0,0,2],[10,28,28,1])
with tf.Session() as sess6:
    print(sess6.run(e))
with tf.Session() as sess7:
    print(sess7.run(f))
with tf.Session() as sess8:
    print(sess8.run(g))

[[[[0.9583621 ]
   [0.18714142]
   [0.82959974]
   ...
   [0.8293865 ]
   [0.7938585 ]
   [0.6970258 ]]

  [[0.44646192]
   [0.15227342]
   [0.6131121 ]
   ...
   [0.6040207 ]
   [0.61499345]
   [0.2602694 ]]

  [[0.9712143 ]
   [0.03032577]
   [0.7001115 ]
   ...
   [0.7883072 ]
   [0.6429846 ]
   [0.6856935 ]]

  ...

  [[0.8429011 ]
   [0.70416284]
   [0.21695554]
   ...
   [0.34642553]
   [0.6554638 ]
   [0.35371816]]

  [[0.52069855]
   [0.28261757]
   [0.22898781]
   ...
   [0.90501213]
   [0.9394374 ]
   [0.6093409 ]]

  [[0.8405267 ]
   [0.8455856 ]
   [0.9805963 ]
   ...
   [0.11807024]
   [0.26719356]
   [0.45180392]]]


 [[[0.6296514 ]
   [0.3672918 ]
   [0.9616275 ]
   ...
   [0.48465335]
   [0.13649213]
   [0.2006464 ]]

  [[0.6890216 ]
   [0.6405444 ]
   [0.80846477]
   ...
   [0.8266752 ]
   [0.37035537]
   [0.33008575]]

  [[0.0426178 ]
   [0.82622254]
   [0.45677328]
   ...
   [0.14929223]
   [0.09542727]
   [0.10382128]]

  ...

  [[0.90272033]
   [0.08748746]
   [0.3

In [25]:
#切片是原始数组视图。这就意味着，如果做任何修改，原始都会跟着更改

In [ ]:
#索引取出的是真是数据不会因此改动而改动

In [26]:
#4阶，shape(10,28,28,3)